version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amigoscodedemo
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  snowplow-micro:
    image: snowplow/snowplow-micro:1.1.1
    volumes:
      - ./snowplow/micro:/config
    restart: always
    ports:
      - "9090:9090"
    command: "--collector-config /config/micro.conf --iglu /config/iglu.json"
