version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amigoscodedemo
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  iglu-db:
    container_name: postgres-iglu
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: igludb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5433:5432"
    logging:
      options:
        max-size: 1G

  iglu-server:
    container_name: iglu-server
    image: snowplow-docker-registry.bintray.io/snowplow/iglu-server:0.6.0-rc3
    entrypoint: /usr/local/bin/wait-for-postgres.sh postgres --config /snowplow/config/application.conf
    depends_on:
      - iglu-db
    ports:
      - "8081:8080"
    volumes:
      - "./wait-for-postgres.sh:/usr/local/bin/wait-for-postgres.sh"
      - "../application.conf:/snowplow/config/application.conf"
    logging:
      options:
        max-size: 1G
