spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootappdb.c3gixclxsyqd.eu-west-2.rds.amazonaws.com:5432/amigoscodedemo
    username: krasy8
    password: password
    pool-size: 30
